@startuml

title Empty Diagram - CIM.Line


Class Line <line>{
IdentifiedObject.name
IdentifiedObject._Names.CircuitName
Line.Region
}

Class ACLineSegment{
IdentifiedObject.name
PowerSystemResource.PSRRoles
PowerSystemResource.PSRType
ConductingEquipment.BaseVoltage
PowerSystemResource.Location
}

Class Terminal <line>{
Terminal.ConductingEquipment
Terminal.ConnectivityNode
Terminal.sequenceNumber

}
Class ConnectivityNode{
}

Class PSRRole{
PSRRole.PSRRoleType
IdentifiedObject.name
IdentifiedObject.mRID
}

Class PSRRoleType{
IdentifiedObject.name
IdentifiedObject.mRID
}

Class BaseVoltage{
IdentifiedObject.name
IdentifiedObject.mRID
BaseVoltage.nominalVoltage
}

Class Location <line>{
  IdentifiedObject.mRID
  IdentifiedObject.name
  Location.CoordinateSystem
  Location.Rotation
 }

Class PositionPoint<line>{
  PositionPoint.sequenceNumber
  PositionPoint.xPosition
  PositionPoint.yPosition
  PositionPoint.zPosition
  PositionPoint.Location

}


ACLineSegment::PowerSystemResource.PSRRoles-->PSRRole
ACLineSegment::PowerSystemResource.PSRType-->PSRType
ACLineSegment::ConductingEquipment.BaseVoltage-->BaseVoltage
ACLineSegment::PowerSystemResource.Location-->Location
Terminal::Terminal.ConnectivityNode-->ConnectivityNode
Terminal::Terminal.ConnectivityNode-->ACLineSegment
PSRRole::PSRRoleType-->PSRRoleType
PositionPoint::PositionPoint.Location-->Location

@enduml